version: '3.8'

services:
  web:
    build: .
    image: my-node-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
