import { Quicksand } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navBar'

const quicksand = Quicksand({ 
  subsets: ['latin'],
  weight:['700'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={quicksand.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
